<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup> 
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <Version>1.0.2</Version>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <Authors>Cyro</Authors>
    <Product>VRCFT Interface</Product>
    <Description>VRCFT OSC face and eye tracking support for Resonite</Description>
    <Copyright>Copyright (c) 2023 Riley Fields</Copyright>
  </PropertyGroup>

  <!--This will test for the default Steam installation paths for Resonite on Windows and Linux.-->
  <PropertyGroup Condition="'$(ResonitePath)'==''">
    <ResonitePath Condition="'$(OS)' == 'Windows_NT' and Exists('C:\Program Files (x86)\Steam\steamapps\common\Resonite\')">C:\Program Files (x86)\Steam\steamapps\common\Resonite\</ResonitePath> 
    <ResonitePath Condition="'$(OS)' != 'Windows_NT' and Exists('$(HOME)/.local/share/Steam/steamapps/common/Resonite/')">$(HOME)/.local/share/Steam/steamapps/common/Resonite/</ResonitePath>
    <!--If neither path above exists, you can define your custom Resonite install directory here -->
    <ResonitePath Condition="'$(ResonitePath)'==''">/Custom/Resonite/Install/Path</ResonitePath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ResoniteModLoader">
      <HintPath>$(ResonitePath)Libraries\ResoniteModLoader.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(ResonitePath)0Harmony.dll</HintPath>
      <HintPath Condition="Exists('$(ResonitePath)rml_libs\0Harmony.dll')">$(ResonitePath)rml_libs\0Harmony.dll</HintPath>
      <HintPath Condition="Exists('$(ResonitePath)Libraries\0Harmony.dll')">$(ResonitePath)Libraries\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="FrooxEngine">
      <HintPath>$(ResonitePath)Resonite_Data\Managed\FrooxEngine.dll</HintPath>
    </Reference>
    <Reference Include="Elements.Core">
      <HintPath>$(ResonitePath)Resonite_Data\Managed\Elements.Core.dll</HintPath>
    </Reference>
    <Reference Include="Elements.Assets">
      <HintPath>$(ResonitePath)Resonite_Data\Managed\Elements.Assets.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(ResonitePath)Resonite_Data\Managed\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityFrooxEngineRunner">
      <HintPath>$(ResonitePath)Resonite_Data\Managed\UnityFrooxEngineRunner.dll</HintPath>
    </Reference>
    <Reference Include="Re-Sounding">
      <HintPath>$(ResonitePath)rml_libs\Re-Sounding.dll</HintPath>
    </Reference>
    <PackageReference Include="VRChat.OSCQuery" Version="0.0.7" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Rug.Osc" Version="1.2.5" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Copy SourceFiles="$(OutDir)$(TargetFileName)" DestinationFolder="$(ResonitePath)rml_mods" />
    <Copy SourceFiles="$(OutDir)Re-Sounding.dll" DestinationFolder="$(ResonitePath)rml_libs" />
  </Target>
</Project>
